default_backend: local
rate_limiter:                                                                                                                                     
    storage: redis  # "memory" or "redis"                                                                                                          
    redis_url: redis://localhost:6379  # only used if storage is "redis"    
backends:
  local:
    type: local
    url: http://127.0.0.1:8081
  modal:
    type: modal
    url: https://vivianxu1999--relay-llama-server-web.modal.run
  modal_vllm:
    type: vllm
    url: https://YOUR_MODAL_VLLM_URL